tasks:
  - name: Install required packages & Open Jupyter Notebook
    init: pip install -r requirements.txt
    command: gp open quickstart-demo.ipynb

vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
    - charliermarsh.ruff
    - dustypomerleau.yarra-valley
    - fill-labs.dependi
    - github.copilot
    - github.copilot-chat
    - github.vscode-github-actions
    - grapecity.gc-excelviewer
    - humao.rest-client
    - mechatroner.rainbow-csv
    - ms-python.black-formatter
    - ms-python.debugpy
    - ms-python.isort
    - ms-python.mypy-type-checker
    - ms-python.vscode-pylance
